### ISSUE TITLE
Write scripts for extracting and merging terms

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/Experimental-OBO-Core#1]
We should fetch the Google Sheet as TSV, store it in Git, then use it to drive a ROBOT workflow that fetches and extracts the terms from the right ontologies. Best to use the ODK directory layout. Let's stick to ROBOT, Make, and standard Unix utilities as far as possible, and only jump to Python if needed. We can tweak the Google Sheet as needed.

**Comment by rctauber** [comment]
Just added the Makefile - I did a few test builds with it, but it's pretty network-dependent for extracting from ChEBI, NCBITaxon, GAZ, etc...

Right now, I'm using SLME BOT method to extract. This can be changed if you think STAR would be better? I would imagine we want to maintain the logic, so probably not MIREOT.

Here's the steps of the Makefile:
1. Download the Google sheet
2. Create a list of ontologies to extract from
3. Create a `[ONT]-terms.txt` for each of the ontologies
4. Extract `[ONT]-terms.txt` for each ontology in the list
5. Extract all classes from BFO, annotation properties from IAO, and object properties from RO
6. Create a `catalog-v001.xml` that maps the modules to their IRIs
7. Create a SPARQL CONSTRUCT query to add the import statements to an empty ontology
8. Build `obo-core.owl` by running the CONSTRUCT query and collapsing the import closure
9. Clean up - remove build files

I ran `reason` over one of the test builds (excluding larger ontologies) and the ontology is inconsistent, so that will be something to look into...

**Comment by cmungall** [comment]
I think the inclusion of GAZ was a mistake. GAZ *should* be instances, but due to the fact Michael liked editing in oboedit there was never really a distinction. Everything you need should be in ENVO.

The size of NCBITaxon is constantly an issue. But I think the taxslim product (see http://obofoundry.org/ontology/ncbitaxon.html) should suffice for our purposes here (it does require making the Makefile a bit less generic).

**Comment by cmungall** [comment]
For incoherent ontologies, this would be a good time to give https://github.com/ontodev/robot/pull/354 a shot

**Comment by rctauber** [comment]
I checked in ENVO and location is a property, rather than a class. I'm not sure what the use-case of including 'geographic location' as a class is, but I could understand 'location' as a property.

I'll play with the taxslim product - it would reduce the load time.

**Comment by rctauber** [comment]
We have moved to manually creating the core for now.
